---
arch_external_dev2: Data
arch_external_dev3: TOSHIBA EXT
arch_external_dev4: 3dc52ee3-d7b3-4eb0-86aa-8237ca5c0ad7
# backup files
config_files_backup_env: # home folder only
  - ~/.local/share/nvim/trailblazer
  - ~/.local/share/nvim/dirsession
  - ~/.local/share/nvim/fzf-lua
  - ~/.local/share/nvim/gp
  - ~/.local/share/nvim/codecompanion-history
  - ~/.local/share/zoxide
  - ~/.cache/nvim/fundo
  - ~/.cache/nvim/undodir
  - ~/.cache/nvim/shadadir
  - ~/.cache/nvim/gp
  - ~/.local/state/nvim/shada
  - ~/.local/share/fish/fish_history
  - ~/.ssh/config
  - ~/.bash_history
  - ~/.config/REAPER
pkm_backup_env:
  - ~/PKM
  - ~/.local/share/promnesia
seedvault_main_backup_env:
  - /storage/emulated/0/.SeedVaultAndroidBackup
phone_photos_backup_env:
  - /storage/emulated/0/DCIM/Camera
audio_pjs_backup_env:
  - ~/external/audio-pjs
notes_backup_env:
  - ~/external/notes/foam
reader_annotations_backup_env:
  - /storage/emulated/0/note
root_backup_env:
  - /etc/hosts
  - /etc/ansible/hosts
  - /etc/default/grub
  - /etc/udev/udev.conf
  - /etc/default/cpupower
  - /etc/sysctl.d/99-sysctl.conf
  - /etc/sysctl.d/90-max_user_watches.conf
  - /etc/security/limits.d/95-pipewire.conf
  - /etc/makepkg.conf
  - /etc/mkinitcpio.conf
  - /etc/fstab
  - /etc/X11/xorg.conf.d/80-igpu-primary-egpu-offload.conf
  - /var/log/pacman.log
  - /var/log/journal
  - /etc/pacman.conf
  - /etc/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf
  - /etc/udev/rules.d/80-nvidia-pm.rules
  - /usr/share/applications/DaVinciResolve.desktop
  - /etc/modprobe.d/blacklist-nouveau.conf
bw_backup_env:
  - ~/bw

# borg repos
dev1_audio_pjs_borg_repo: ssh://borg/~/backups/audio-pjs
dev1_config_files_borg_repo: ssh://borg/~/backups/config-files
dev1_pkm_borg_repo: ssh://borg/~/backups/PKM
dev1_notes_borg_repo: ssh://borg/~/backups/notes
dev1_seedvault_borg_repo: ssh://borg/~/backups/seedvault-main
dev1_phone_photos_borg_repo: ssh://borg/~/backups/phone-photos
dev1_reader_annotations_borg_repo: ssh://borg/~/backups/reader-annotations
dev1_root_borg_repo: ssh://borg/~/backups/root-backup
dev1_bw_borg_repo: ssh://borg/~/backups/bw-backup
dev2_audio_pjs_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/backups/audio-pjs
dev2_config_files_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/backups/config-files
dev2_pkm_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/backups/PKM
dev2_notes_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/backups/notes
dev2_root_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/backups/root-backup
dev2_bw_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/backups/bw-backup
dev3_audio_pjs_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/backups/audio-pjs
dev3_config_files_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/backups/config-files
dev3_pkm_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/backups/PKM
dev3_notes_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/backups/notes
dev3_root_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/backups/root-backup
dev3_bw_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/backups/bw-backup

otherlinux_borg_repos_env:
  - repo: "{{ dev1_seedvault_borg_repo }}"
    files: "{{ seedvault_main_backup_env }}"
    sh_template: autogenerated-dev1-seedvault-main
  - repo: "{{ dev1_phone_photos_borg_repo }}"
    files: "{{ phone_photos_backup_env }}"
    sh_template: autogenerated-dev1-phone-photos
  - repo: "{{ dev1_reader_annotations_borg_repo }}"
    files: "{{ reader_annotations_backup_env }}"
    sh_template: autogenerated-dev1-reader-annotations

archlinux_borg_repos_env:
  - repo: "{{ dev1_audio_pjs_borg_repo }}"
    files: "{{ audio_pjs_backup_env }}"
    sh_template: autogenerated-dev1-audio-pjs
  - repo: "{{ dev1_config_files_borg_repo }}"
    files: "{{ config_files_backup_env }}"
    sh_template: autogenerated-dev1-config-files
  - repo: "{{ dev1_pkm_borg_repo }}"
    files: "{{ pkm_backup_env }}"
    sh_template: autogenerated-dev1-PKM
  - repo: "{{ dev1_notes_borg_repo }}"
    files: "{{ notes_backup_env }}"
    sh_template: autogenerated-dev1-notes
  - repo: "{{ dev1_bw_borg_repo }}"
    files: "{{ bw_backup_env }}"
    sh_template: autogenerated-dev1-bw-backup
  - repo: "{{ dev2_audio_pjs_borg_repo }}"
    files: "{{ audio_pjs_backup_env }}"
    sh_template: autogenerated-dev2-audio-pjs
  - repo: "{{ dev2_config_files_borg_repo }}"
    files: "{{ config_files_backup_env }}"
    sh_template: autogenerated-dev2-config-files
  - repo: "{{ dev2_pkm_borg_repo }}"
    files: "{{ pkm_backup_env }}"
    sh_template: autogenerated-dev2-PKM
  - repo: "{{ dev2_notes_borg_repo }}"
    files: "{{ notes_backup_env }}"
    sh_template: autogenerated-dev2-notes
  - repo: "{{ dev2_bw_borg_repo }}"
    files: "{{ bw_backup_env }}"
    sh_template: autogenerated-dev2-bw-backup
  - repo: "{{ dev3_audio_pjs_borg_repo }}"
    files: "{{ audio_pjs_backup_env }}"
    sh_template: autogenerated-dev3-audio-pjs
  - repo: "{{ dev3_config_files_borg_repo }}"
    files: "{{ config_files_backup_env }}"
    sh_template: autogenerated-dev3-config-files
  - repo: "{{ dev3_pkm_borg_repo }}"
    files: "{{ pkm_backup_env }}"
    sh_template: autogenerated-dev3-PKM
  - repo: "{{ dev3_notes_borg_repo }}"
    files: "{{ notes_backup_env }}"
    sh_template: autogenerated-dev3-notes
  - repo: "{{ dev3_bw_borg_repo }}"
    files: "{{ bw_backup_env }}"
    sh_template: autogenerated-dev3-bw-backup

archlinux_borg_root_repos_env:
  - borg_repo: "{{ dev1_root_borg_repo }}"
    files: "{{ root_backup_env }}"
    sh_template: autogenerated-dev1-root
  - borg_repo: "{{ dev2_root_borg_repo }}"
    files: "{{ root_backup_env }}"
    sh_template: autogenerated-dev2-root
  - borg_repo: "{{ dev3_root_borg_repo }}"
    files: "{{ root_backup_env }}"
    sh_template: autogenerated-dev3-root
