---
arch_external_dev2: Data
arch_external_dev3: TOSHIBA EXT
arch_external_dev4: 3dc52ee3-d7b3-4eb0-86aa-8237ca5c0ad7
# backup files
config_files_backup_env: # home folder only
  - ~/.local/share/nvim/trailblazer
  - ~/.local/share/nvim/dirsession
  - ~/.local/share/nvim/fzf-lua
  - ~/.local/share/nvim/gp
  - ~/.local/share/nvim/codecompanion-history
  - ~/.local/share/zoxide
  - ~/.cache/nvim/fundo
  - ~/.cache/nvim/undodir
  - ~/.cache/nvim/shadadir
  - ~/.cache/nvim/gp
  - ~/.local/state/nvim/shada
  - ~/.local/share/fish/fish_history
  - ~/.ssh/config
  - ~/.bash_history
  - ~/.config/REAPER
  - ~/data/work/cf/.gitconfig
  - ~/dotfiles/.gitconfig
pkm_backup_env:
  - ~/data/PKM
  - ~/.local/share/promnesia
seedvault_main_backup_env:
  - /storage/emulated/0/.SeedVaultAndroidBackup
phone_photos_backup_env:
  - /storage/emulated/0/DCIM/Camera
audio_pjs_backup_env:
  - ~/data/audio-pjs
notes_backup_env:
  - ~/data/notes/foam
reader_annotations_backup_env:
  - /storage/emulated/0/note
root_backup_env:
  - /etc/hosts
  - /etc/ansible/hosts
  - /etc/default/grub
  - /etc/udev/udev.conf
  - /etc/default/cpupower
  - /etc/sysctl.d/99-sysctl.conf
  - /etc/sysctl.d/90-max_user_watches.conf
  - /etc/security/limits.d/95-pipewire.conf
  - /etc/makepkg.conf
  - /etc/mkinitcpio.conf
  - /etc/fstab
  - /etc/X11/xorg.conf.d/80-igpu-primary-egpu-offload.conf
  - /var/log/pacman.log
  - /var/log/journal
  - /etc/pacman.conf
  - /etc/X11/xorg.conf.d/10-nvidia-drm-outputclass.conf
  - /etc/udev/rules.d/80-nvidia-pm.rules
  - /usr/share/applications/DaVinciResolve.desktop
  - /etc/modprobe.d/blacklist-nouveau.conf
bw_backup_env:
  - ~/data/bw

# borg repos
dev2_audio_pjs_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/data/backups/audio-pjs
dev2_config_files_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/data/backups/config-files
dev2_pkm_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/data/backups/PKM
dev2_notes_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/data/backups/notes
dev2_root_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/data/backups/root-backup
dev2_bw_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev2 }}/data/backups/bw-backup
dev3_audio_pjs_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/data/backups/audio-pjs
dev3_config_files_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/data/backups/config-files
dev3_pkm_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/data/backups/PKM
dev3_notes_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/data/backups/notes
dev3_root_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/data/backups/root-backup
dev3_bw_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev3 }}/data/backups/bw-backup
dev4_audio_pjs_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev4 }}/data/backups/audio-pjs
dev4_config_files_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev4 }}/data/backups/config-files
dev4_pkm_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev4 }}/data/backups/PKM
dev4_notes_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev4 }}/data/backups/notes
dev4_seedvault_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev4 }}/data/backups/seedvault-main
dev4_phone_photos_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev4 }}/data/backups/phone-photos
dev4_reader_annotations_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev4 }}/data/backups/reader-annotations
dev4_root_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev4 }}/data/backups/root-backup
dev4_bw_borg_repo: /run/media/{{ ansible_env.USER }}/{{ arch_external_dev4 }}/data/backups/bw-backup

otherlinux_borg_repos_env:
  - repo: "{{ dev4_seedvault_borg_repo }}"
    device: "{{ arch_external_dev4 }}"
    files: "{{ seedvault_main_backup_env }}"
    sh_template: autogenerated-dev4-seedvault-main
  - repo: "{{ dev4_phone_photos_borg_repo }}"
    device: "{{ arch_external_dev4 }}"
    files: "{{ phone_photos_backup_env }}"
    sh_template: autogenerated-dev4-phone-photos
  - repo: "{{ dev4_reader_annotations_borg_repo }}"
    device: "{{ arch_external_dev4 }}"
    files: "{{ reader_annotations_backup_env }}"
    sh_template: autogenerated-dev4-reader-annotations

archlinux_borg_repos_env:
  - repo: "{{ dev4_audio_pjs_borg_repo }}"
    device: "{{ arch_external_dev4 }}"
    files: "{{ audio_pjs_backup_env }}"
    sh_template: autogenerated-dev4-audio-pjs
    keyrings:
      passkey: audio-pjs
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev4_config_files_borg_repo }}"
    device: "{{ arch_external_dev4 }}"
    files: "{{ config_files_backup_env }}"
    sh_template: autogenerated-dev4-config-files
    keyrings:
      passkey: config-files
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev4_pkm_borg_repo }}"
    device: "{{ arch_external_dev4 }}"
    files: "{{ pkm_backup_env }}"
    sh_template: autogenerated-dev4-PKM
    keyrings:
      passkey: PKM
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev4_notes_borg_repo }}"
    device: "{{ arch_external_dev4 }}"
    files: "{{ notes_backup_env }}"
    sh_template: autogenerated-dev4-notes
    keyrings:
      passkey: notes
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev4_bw_borg_repo }}"
    device: "{{ arch_external_dev4 }}"
    files: "{{ bw_backup_env }}"
    sh_template: autogenerated-dev4-bw-backup
    keyrings:
      passkey: bw-backup
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev2_audio_pjs_borg_repo }}"
    device: "{{ arch_external_dev2 }}"
    files: "{{ audio_pjs_backup_env }}"
    sh_template: autogenerated-dev2-audio-pjs
    keyrings:
      passkey: audio-pjs
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev2_config_files_borg_repo }}"
    device: "{{ arch_external_dev2 }}"
    files: "{{ config_files_backup_env }}"
    sh_template: autogenerated-dev2-config-files
    keyrings:
      passkey: config-files
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev2_pkm_borg_repo }}"
    device: "{{ arch_external_dev2 }}"
    files: "{{ pkm_backup_env }}"
    sh_template: autogenerated-dev2-PKM
    keyrings:
      passkey: PKM
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev2_notes_borg_repo }}"
    device: "{{ arch_external_dev2 }}"
    files: "{{ notes_backup_env }}"
    sh_template: autogenerated-dev2-notes
    keyrings:
      passkey: notes
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev2_bw_borg_repo }}"
    device: "{{ arch_external_dev2 }}"
    files: "{{ bw_backup_env }}"
    sh_template: autogenerated-dev2-bw-backup
    keyrings:
      passkey: bw-backup
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev3_audio_pjs_borg_repo }}"
    device: "{{ arch_external_dev3 }}"
    files: "{{ audio_pjs_backup_env }}"
    sh_template: autogenerated-dev3-audio-pjs
    keyrings:
      passkey: audio-pjs
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev3_config_files_borg_repo }}"
    device: "{{ arch_external_dev3 }}"
    files: "{{ config_files_backup_env }}"
    sh_template: autogenerated-dev3-config-files
    keyrings:
      passkey: config-files
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev3_pkm_borg_repo }}"
    device: "{{ arch_external_dev3 }}"
    files: "{{ pkm_backup_env }}"
    sh_template: autogenerated-dev3-PKM
    keyrings:
      passkey: PKM
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev3_notes_borg_repo }}"
    device: "{{ arch_external_dev3 }}"
    files: "{{ notes_backup_env }}"
    sh_template: autogenerated-dev3-notes
    keyrings:
      passkey: notes
      folder: borg-passwords
      wallet: kdewallet
  - repo: "{{ dev3_bw_borg_repo }}"
    device: "{{ arch_external_dev3 }}"
    files: "{{ bw_backup_env }}"
    sh_template: autogenerated-dev3-bw-backup
    keyrings:
      passkey: bw-backup
      folder: borg-passwords
      wallet: kdewallet

archlinux_borg_root_repos_env:
  - borg_repo: "{{ dev4_root_borg_repo }}"
    device: "{{ arch_external_dev4 }}"
    files: "{{ root_backup_env }}"
    sh_template: autogenerated-dev4-root
    keyrings:
      passkey: root-backup
      folder: borg-root-passwords
      wallet: kdewallet
  - borg_repo: "{{ dev2_root_borg_repo }}"
    device: "{{ arch_external_dev2 }}"
    files: "{{ root_backup_env }}"
    sh_template: autogenerated-dev2-root
    keyrings:
      passkey: root-backup
      folder: borg-root-passwords
      wallet: kdewallet
  - borg_repo: "{{ dev3_root_borg_repo }}"
    device: "{{ arch_external_dev3 }}"
    files: "{{ root_backup_env }}"
    sh_template: autogenerated-dev3-root
    keyrings:
      passkey: root-backup
      folder: borg-root-passwords
      wallet: kdewallet
