---
extension_chrome_regex_search: bpelaihoicobbkgmhcbikncnpacdbknn
extension_floccus: fnaicdffflnofjppbagibeoednhnbjhg
extension_monolith: koalogomkahjlabefiglodpnhhkokekg
local_extension_show_tab_numbers: pcjgbnebecbfkjidmjlfcjnjacekbolg
local_extension_new_tab_redirect: dgnkopfojfndphccpgfmnapknkfanooc
local_extension_vimium: gdianalakofefgedjabillacncbbpeoh
local_extension_promnesia: phjbangbkhghaapdoklnbbipfkdmdjgk
local_hypothesis_extension: eajkghkpdleogcecilhonjdokiipfmdb
local_playwright_mcp: jakfalbnbhgkpmoaakfflhflbfpkailf
local_playwright_mcp_version: 0.0.64

browser_local_extensions:
  - name: hypothesis-extension
    path: "{{ prefix | default(ansible_facts.env.HOME) }}/data/repos/hypothesis-extension/build"
    repo: https://github.com/hypothesis/browser-extension
    hide: true
  - name: promnesia
    path: "{{ prefix | default(ansible_facts.env.HOME) }}/data/repos/promnesia/extension/dist/chrome"
    repo: https://github.com/karlicoss/promnesia
  - name: NewTab-Redirect
    path: "{{ prefix | default(ansible_facts.env.HOME) }}/data/repos/NewTab-Redirect"
    repo: https://github.com/jimschubert/NewTab-Redirect
  - name: vimium
    path: "{{ prefix | default(ansible_facts.env.HOME) }}/data/repos/vimium"
    repo: https://github.com/philc/vimium
  - name: chrome-show-tab-numbers
    path: "{{ prefix | default(ansible_facts.env.HOME) }}/data/repos/chrome-show-tab-numbers"
    repo: https://github.com/kg8m/chrome-show-tab-numbers
  - name: playwright-mcp-extension
    repo: https://github.com/microsoft/playwright-mcp
    path: "{{ prefix | default(ansible_facts.env.HOME) }}/data/repos/playwright-mcp/packages/extension/dist"

facebook_react_extension_version: 19.2.0
