---
arch_ruby_version: 3.2.0

extension_chrome_regex_search: bpelaihoicobbkgmhcbikncnpacdbknn
extension_floccus: fnaicdffflnofjppbagibeoednhnbjhg
extension_monolith: koalogomkahjlabefiglodpnhhkokekg
local_extension_react_devtools: nipckbchhibgnbgnabineijogaiegchd
local_extension_show_tab_numbers: egbdjbfggjldijfoahggfipdkpijmmgd
local_extension_new_tab_redirect: jbkaalaijhbkmaffefakjjpphiefocai
local_extension_vimium: dblffdcabmecmgepoideebngccnllhlo
local_extension_promnesia: dmeifochafhcoiolkeadbjgimpamfghc
local_hypothesis_extension: oaefmonehnpgpgggcnifjffikgfchbgp
local_playwright_mcp: jakfalbnbhgkpmoaakfflhflbfpkailf

browser_local_extensions:
  - name: hypothesis-extension
    path: "{{ prefix | default(ansible_env.HOME) }}/repos/hypothesis-extension/build"
    hide: true
  - name: promnesia
    path: "{{ prefix | default(ansible_env.HOME) }}/repos/promnesia/extension/dist/chrome"
  - name: react
    path: "{{ prefix | default(ansible_env.HOME) }}/repos/react/packages/react-devtools-extensions/chrome/build/unpacked"
  - name: NewTab-Redirect
    path: "{{ prefix | default(ansible_env.HOME) }}/repos/NewTab-Redirect"
  - name: vimium
    path: "{{ prefix | default(ansible_env.HOME) }}/repos/vimium"
  - name: chrome-show-tab-numbers
    path: "{{ prefix | default(ansible_env.HOME) }}/repos/chrome-show-tab-numbers"
  - name: playwright-mcp-extension
    path: "{{ prefix | default(ansible_env.HOME) }}/repos/playwright-mcp/extension/dist"

facebook_react_extension_version: 19.2.0
