---
- block:
    - name: Base setup
      ansible.builtin.include_tasks: "{{ item }}"
      with_first_found:
        - files: 10-base-setup.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
  tags: ["10--system--10"]
