---
- name: "[archlinux] Git tools: ensure diff tools"
  become: true
  ansible.builtin.package:
    state: present
    name:
      - difftastic
      - git-delta

- name: "[archlinux] Git tools: downgrade lazygit"
  become: true
  ansible.builtin.command: downgrade --ignore always --prefer-cache 'lazygit=0.57.0' -- --noconfirm
  environment:
    DOWNGRADE_FROM_ALA: "1"
  changed_when: true
