---
- block:
    - name: Setup go tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 130-setup-go-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-130"]
