---
- block:
    - name: Ensure node
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 10-setup-node.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["20-10"]
