---
reaper_mcp_server_setup:
  repo_path: "{{ ansible_env.HOME }}/external/repos/reaper-mcp-server"
  projects_dir: "{{ ansible_env.HOME }}/external/audio-pjs"

figma_mcp_server_setup:
  exe_path: "{{ ansible_env.HOME }}/.volta/tools/image/node/{{ node_system_default_version }}/bin/figma-developer-mcp"
  personal_key: "{{ (mcp_server_figma_key | default({})).stdout | default(None) }}"

figma_mcp_commentary_server_setup:
  exe_path: "{{ ansible_env.HOME }}/.volta/tools/image/node/{{ node_system_default_version }}/bin/mcp-figma-comment-summary"
  personal_key: "{{ (mcp_server_figma_key | default({})).stdout | default(None) }}"

chrome_devtools_mcp_server_setup:
  exe_path: "{{ ansible_env.HOME }}/.volta/tools/image/node/{{ node_system_default_version }}/bin/chrome-devtools-mcp"

playwright_mcp_server_setup:
  exe_path: "{{ ansible_env.HOME }}/.volta/tools/image/node/{{ node_system_default_version }}/bin/mcp-server-playwright"
  auth_key: "{{ (var_playwright_mcp_browser_key | default({})).stdout | default(None) }}"

context7_mcp_server_setup:
  exe_path: "{{ ansible_env.HOME }}/.volta/tools/image/node/{{ node_system_default_version }}/bin/context7-mcp"
