---
- block:
    - name: Setup java tools
      ansible.builtin.include_tasks: "{{ task_file }}"
      with_first_found:
        - files: 150-setup-java-tools.{{ user_os }}.yml
          skip: true
      when: "user_os in ['archlinux']"
      loop_control:
        loop_var: task_file
  tags: ["30-150"]
