---
- name: handler_ensure_swap_file
  become: true
  ansible.builtin.systemd_service:
    scope: system
    name: "{{ var_escaped_swapfile_path.stdout }}.swap"
    enabled: true
    masked: false
    daemon_reload: true
